### ISSUE TITLE
JW.ORG presenting doesn't work on MacOS

### ISSUE THREAD

**Issue by ux-git** [sircharlo/mmm-refactor#121] opened 2024-08-07 20:00 UTC
After each attempt to present jw.org, I keep getting prompted to give screen recording permission, even though I've granted it multiple times and restarted the app several times.

<img width="889" alt="Screenshot 2024-08-07 at 21 53 56" src="https://github.com/user-attachments/assets/496c46a6-5149-4f4f-ac50-27af07313f59">

**Comment by sircharlo** [comment] 2024-08-07 20:14
I believe this is related to https://github.com/electron/electron/pull/43080.
Should get fixed with an upcoming release of Electron. However, it works as expected on Windows!

**Comment by sircharlo** [comment] 2024-08-27 12:56
Should be resolved now. @ux-git please re-open if the issue is still present in v24.8.1!

**Closed by sircharlo** 2024-08-27 12:56 UTC
Labels: awaiting-dep-update
