### ISSUE TITLE
Sorting stop working

### ISSUE THREAD

**Issue by alanfermtz** [sircharlo/mmm-refactor#66] opened 2024-07-09 17:12 UTC
The sorting stop working if you change the day of meeting

How to reproduce:
Initial boot, wait till all updated, It works initially then I change to my endweek and if I tried to sort does not work, and if I change back to the midweek date, also does not work

**Comment by sircharlo** [comment] 2024-07-09 17:41
I can't reproduce this.
Are you doing the same thing I am?

https://github.com/sircharlo/mmm-refactor/assets/1275666/20ef53cf-aa41-4b44-bbbf-1b2939ae6a30

**Comment by alanfermtz** [comment] 2024-07-09 17:50
I am sorry, please try on the left media calendar button to change

**Comment by sircharlo** [comment] 2024-07-09 18:33
Great catch! Thanks!
Fixed in https://github.com/sircharlo/mmm-refactor/commit/52d77cec5d3f12d3263f4336f060da803408007d

**Closed by sircharlo** 2024-07-09 18:33 UTC
